Template changes for 8.0.0
TIBCOSoftware/quickstart-tibco-jaspersoft pull request #17
Opened 2021-12-03 11:23 UTC by avverma19

Cluster:
  a) Added extra parameter of RDS security Group in existing infra template and accordingly updated RDS and new infra templates. This will ensure corect ingress rule to RDS will be created by the template. This might require documentation update as well.
b) Ugraded LauchConfig to Launch Template
c) Remove cfn-bootstrap package install from templates.

Single:
a) Remove cfn-bootstrap package install from templates.

2022-03-09 22:11 UTC, grantbacon-tibco requested changes
A few syntax errors

2022-03-09 22:11 UTC, grantbacon-tibco commented on templates/tibco-jrs-cluster-existing-infrastructure.template
> +        "AWSRegionAMI": {
Should be 'AWSAMIRegionMap'

2022-03-09 22:11 UTC, grantbacon-tibco commented on templates/tibco-jrs-cluster-existing-infrastructure.template
> +        },
the trailing comma should go on the next line

2022-03-09 23:32 UTC, grantbacon-tibco approved these changes

2022-03-10 04:58 UTC, rreddyv-tibco approved these changes

2022-03-10 04:58 UTC, merged